name: test reusing main

on: 
    workflow_dispatch:
    
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testRunner:
    name: Test in ${{ matrix.testMode }} ✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - EditMode
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  noti:
    uses: astraljoker/Unity-GitHub-Actions/.github/workflows/slack-notify.yml@main
