name: Version Test

on: [workflow_dispatch]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  
jobs:
  buildAndroid:
    name: Build for Android 📱
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        with:
          targetPlatform: Android
      - uses: actions/upload-artifact@v2
        with:
          name: build-Android
          path: build/Android
